-- BNHS WELLNESS LEAVE ONLINE DATABASE SETUP
-- Run this in the Supabase SQL Editor.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  teacher_name text not null unique,
  role text not null default 'teacher' check (role in ('teacher','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.wellness_leave (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  leave_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, leave_date)
);

alter table public.profiles enable row level security;
alter table public.wellness_leave enable row level security;

grant select on public.profiles to authenticated;
grant select, insert, delete on public.wellness_leave to authenticated;
grant usage, select on sequence public.wellness_leave_id_seq to authenticated;

drop policy if exists "Authenticated users can view teacher profiles" on public.profiles;
create policy "Authenticated users can view teacher profiles"
on public.profiles for select to authenticated using (true);

drop policy if exists "Authenticated users can view wellness calendar" on public.wellness_leave;
create policy "Authenticated users can view wellness calendar"
on public.wellness_leave for select to authenticated using (true);

drop policy if exists "Teachers can plot only their own wellness leave" on public.wellness_leave;
create policy "Teachers can plot only their own wellness leave"
on public.wellness_leave for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Teachers can remove own leave and admins can remove any leave" on public.wellness_leave;
create policy "Teachers can remove own leave and admins can remove any leave"
on public.wellness_leave for delete to authenticated
using (
  (select auth.uid()) = user_id
  or exists (
    select 1 from public.profiles p
    where p.user_id = (select auth.uid()) and p.role = 'admin' and p.active
  )
);

create or replace function public.enforce_wellness_leave_rules()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  total_used integer;
  date_used integer;
  r record;
  prev_date date := null;
  next_school_date date;
  run_len integer := 0;
  teacher_ok boolean;
begin
  perform pg_advisory_xact_lock(hashtext(new.user_id::text));
  perform pg_advisory_xact_lock(hashtext(new.leave_date::text));

  select exists(
    select 1 from public.profiles p
    where p.user_id = new.user_id and p.active and p.role in ('teacher','admin')
  ) into teacher_ok;
  if not teacher_ok then
    raise exception 'Your teacher profile is not active or has not been configured.';
  end if;

  if extract(isodow from new.leave_date) in (6,7) then
    raise exception 'Saturday and Sunday are unavailable for Wellness Leave.';
  end if;

  select count(*) into date_used from public.wellness_leave where leave_date = new.leave_date;
  if date_used >= 2 then
    raise exception 'This date is already full. Only 2 teachers may take Wellness Leave on the same school day.';
  end if;

  select count(*) into total_used from public.wellness_leave where user_id = new.user_id;
  if total_used >= 5 then
    raise exception 'You have already used all 5 Wellness Leave days.';
  end if;

  for r in
    select d from (
      select leave_date as d from public.wellness_leave where user_id = new.user_id
      union select new.leave_date
    ) q order by d
  loop
    if prev_date is null then
      run_len := 1;
    else
      next_school_date := prev_date + 1;
      while extract(isodow from next_school_date) in (6,7) loop
        next_school_date := next_school_date + 1;
      end loop;
      if r.d = next_school_date then run_len := run_len + 1; else run_len := 1; end if;
    end if;
    if run_len > 3 then
      raise exception 'Maximum consecutive Wellness Leave is 3 school days.';
    end if;
    prev_date := r.d;
  end loop;

  return new;
end;
$$;

drop trigger if exists wellness_leave_rules_trigger on public.wellness_leave;
create trigger wellness_leave_rules_trigger
before insert on public.wellness_leave
for each row execute function public.enforce_wellness_leave_rules();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='wellness_leave'
  ) then
    alter publication supabase_realtime add table public.wellness_leave;
  end if;
end $$;

-- Create teacher accounts in Supabase Authentication > Users,
-- then add matching rows in public.profiles using each user's UUID.
-- Never put a service-role/secret key in browser files.